# Generated by Django 5.2.4 on 2025-10-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_chatmessage_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recentlyviewed',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recentlyviewed',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
    ]
