# D:\2312040-wfp\productcatalog_project\productcatalog\settings.py
"""
Django settings for productcatalog project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ok4qb&7cb@#w3vk@4sg(!!(ng32gz&8=w=kwvwt&*jjhn&ahwc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'store',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ProfileCompletionMiddleware',
]

ROOT_URLCONF = 'productcatalog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'  # <-- ADD THE ROOT TEMPLATES DIR
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart', # <-- ADD THIS LINE
            ],
        },
    },
]

WSGI_APPLICATION = 'productcatalog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (User-uploaded content)
MEDIA_URL = '/media/'  # <-- ADD THIS
MEDIA_ROOT = BASE_DIR / 'media'  # <-- ADD THIS

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'product_list' # Redirect to home page after login
LOGOUT_REDIRECT_URL = 'product_list' # Redirect to home page after logout
# Cart session ID
CART_SESSION_ID = 'cart'

# D:\2312040-wfp\productcatalog_project\productcatalog\settings.py
# Add these lines at the end of the file

# Razorpay Configuration
RAZORPAY_KEY_ID = 'rzp_test_RbkQjexLuLpwLO'
RAZORPAY_KEY_SECRET = 'ezLTmOeQn7eYEK047foaBAD3'

# College Email Domains for Student Discounts
COLLEGE_EMAIL_DOMAINS = [
    'college.edu',
    'university.edu',
    'student.edu',
    'edu.in',
    'ac.in',
    'iit.ac.in',
    'nit.ac.in',
    'iiit.ac.in',
    'bits-pilani.ac.in',
    'vit.ac.in',
    'srmist.edu.in',
    'annauniv.edu',
    'tnau.ac.in',
    'bharathiaruniversity.ac.in',
    'mkuniversity.ac.in',
    'maduraiuniversity.ac.in',
    'periyaruniversity.ac.in',
    'bharathidasanuniversity.ac.in',
    'alagappauniversity.ac.in',
    'manonmaniam.ac.in',
    'annauniv.edu.in',
    'tn.gov.in',  # Tamil Nadu Government Colleges
]

# Gemini AI settings
GEMINI_API_KEY = 'AIzaSyDvOSLuGs-jEdN6Pc4KxHYG6oy9url6-kc'
